"""Add Asana features tables

Revision ID: 1fbf2b171d6a
Revises: 001
Create Date: 2026-02-04 19:30:07.057528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbf2b171d6a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Goal table
    op.create_table('goal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('target_date', sa.Date(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('status', sa.String(), nullable=False, server_default='on_track'),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('parent_goal_id', sa.Integer(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['parent_goal_id'], ['goal.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_workspace_id', 'goal', ['workspace_id'], unique=False)
    op.create_index('ix_goal_project_id', 'goal', ['project_id'], unique=False)
    
    # Milestone table
    op.create_table('milestone',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('goal_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('completed_date', sa.Date(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_milestone_goal_id', 'milestone', ['goal_id'], unique=False)
    op.create_index('ix_milestone_project_id', 'milestone', ['project_id'], unique=False)
    
    # TaskTemplate table
    op.create_table('tasktemplate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('title_template', sa.String(), nullable=False),
        sa.Column('description_template', sa.String(), nullable=True),
        sa.Column('priority', sa.String(), nullable=False, server_default='medium'),
        sa.Column('estimated_hours', sa.Float(), nullable=True),
        sa.Column('default_tags', sa.String(), nullable=True),
        sa.Column('subtasks_json', sa.String(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('is_shared', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('use_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasktemplate_workspace_id', 'tasktemplate', ['workspace_id'], unique=False)
    
    # FocusTask table
    op.create_table('focustask',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('focus_date', sa.Date(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_focustask_user_id', 'focustask', ['user_id'], unique=False)
    op.create_index('ix_focustask_task_id', 'focustask', ['task_id'], unique=False)
    op.create_index('ix_focustask_focus_date', 'focustask', ['focus_date'], unique=False)
    
    # ActivityLog table (if not exists - may already be in DB)
    # Only create if table doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'activitylog' not in inspector.get_table_names():
        op.create_table('activitylog',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('workspace_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('action_type', sa.String(), nullable=False),
            sa.Column('entity_type', sa.String(), nullable=False),
            sa.Column('entity_id', sa.Integer(), nullable=False),
            sa.Column('details', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_activitylog_created_at', 'activitylog', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focustask')
    op.drop_table('tasktemplate')
    op.drop_table('milestone')
    op.drop_table('goal')
    # Note: activitylog not dropped as it may have existed before
    # ### end Alembic commands ###
